ARG BASE_IMAGE=nats:2.10.12-windowsservercore-1809
FROM $BASE_IMAGE AS base

FROM mcr.microsoft.com/windows/nanoserver:1809
ENV NATS_DOCKERIZED 1

COPY --from=base C:\\nats-server.exe C:\\nats-server.exe
COPY nats-server.conf C:\\nats-server.conf

EXPOSE 4222 8222 6222
ENTRYPOINT ["C:\\nats-server.exe"]
CMD ["--config", "nats-server.conf"]
